cmake_minimum_required (VERSION 3.11)

if(TARGET hello::hello)
    set(hello_FOUND TRUE)
elseif(TARGET CONAN_PKG::hello)
    add_library(hello::hello INTERFACE IMPORTED)
    target_link_libraries(hello::hello INTERFACE CONAN_PKG::hello)
    set(hello_FOUND TRUE)
else()
    set(hello_FOUND FALSE)
    if(hello_FIND_REQUIRED)
        message(FATAL_ERROR "Unable to find hello")
    endif()
endif()